### ISSUE TITLE
Deprecated JDBC driver warning

### ISSUE THREAD

**Issue by mindgam3s** [DiscordSRV/DiscordSRV#1089]
Console displays
```
[16:12:02] [DiscordSRV - Initialization/WARN]: Loading class 'com.mysql.jdbc.Driver'. This is deprecated. The new driver class is 'com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
```

git-Paper-584 (MC: 1.16.5)

https://bin.scarsz.me/087ff1a9-a4ce-466a-9f92-5a9ce90852ca#F4HqnXDIBQUyWA92LlISsdjxwSUFj3ic

**Comment by PlayingWithPi** [comment]
Seems like this is an ongoing issue, wondering if anyone is working on it.
git-Paper-187 (MC: 1.18.1)

**Comment by SatoriHoshiAiko** [comment]
I investigated this and resolved the source of this warning.

In my case to replicate the issue, I was using MariaDB and not mysql.

The warning happens actually more frequently when the driver fails to load. I.e. a bad syntax in the configuration such as jdbc:http:/localhost:3306/my_db - In this case missing a :// for :/ - The driver won't load from bad syntax.

But this same issue will happen when you use mariadb. I tried passing jbdc:mariadb://localhost:3306/mydb in the config - In this case, it loaded correctly (because I had mariadb installed) but DiscordSRV noted that mariadb was unsupported and so it would skip.

To resolve - Make sure you are using Mysql (mysql-community-server e.g.) - Follow traditional guidelines to install mysql and have it working. If you need to migrate from mariadb to mysql, be forewarned, you will have to be careful about backing up your databases before switching, **You can lose your database data!!**


In my case, I had no existing databases I didn't care to lose - And so I uninstalled mariadb, installed mysql. Using jbdc:mysql://localhost:3306/mydb - It now works, it does not fail to load the driver because I am using mysql and not mariadb.

For anyone who care to know how to resolve this.

Also this "bug" - It is a warning and in fact it will be follow in some form by Cannot make connection. Well indeed it can't, DiscordSRV JBDC is not even using mariadb as of yet it would seem. How can is load a mysql driver when it runs mariadb? They are similar but not same. But a working Mysql server and correct database credentials? Yes it will work. Double check your syntax. Double check your login credentials. Backup your database if you have to migrate.

BTW - This is an amazing feature when using a proxy like Velocity. Syncing account linking across backends add a really nifty security feature for multiple backend proxies. I use the account linking in order to add a "Must be in server or use my bot" - security policy. Well you will have to constantly relink your account with each backend (I am using papermc 1.19.2 and velocity).

I really love this, and I was so confused as to why this was working on my Debian system and not my kali system. Resolution - Be sure you have a working mysql server and *not* mariadb, you will even be able to use the mysql command and login with JBDC credentials, but mariadb will fail at this bug.

Hope this helps.

**Comment by Vankka** [comment]
@SatoriHoshiAiko The MySQL JDBC driver is already compatible MariaDB (see [MariaDB's website](https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/#replacement-for-mysql)), there was probably something else wrong in your setup. 

Connecting all backends to the same MySQL database makes them share their linked accounts, thus avoiding needing to relink on every backend server.

This warning message only appears because the Minecraft server has a newer version of the MySQL driver (than what is included in some older server versions), and does not effect it's functionality whatsoever. Either way I pushed a commit to avoid the warning since the PR overhauling linked account connectivity has stalled.

**Comment by SatoriHoshiAiko** [comment]
Thanks yes I noticed it still showed on MySQL after a restart. Was still
debugging.

100% it’s a new driver.

Oddly, this account link via MySQL database is working on my Debian 11 just
fine. But failing on my Kali system. (I run two Velocity proxies on each
system).

Kali typically has compatibility issues anyway since it is not always a
typical Debian system but Debian based, with minor incongruencies leading
to bugs.

I haven’t checked if the MySQL setup is working yet for cross checking on
account link. Actually my game pass has expired and that’s my main stopping
point at the moment.

As long as the newer driver is loading then it would be fine. But I did
when testing before have issues having to renter the code to each server
and assumed it was actually failing to make a database connection from this
error.

I do get [JDA] Connection established

I.e. I have a good user and password

I skipped manually adding a table prefix in the assumption that this may
get added by DiscordSRV when the connection is made by default. But the
next step would be testing it against an existing table (adding “CREATE
TABLE discordsrv_;”) to match the config

I bet the last statement is causing my issue more than anything. I just
haven’t been able to test against it without a working Minecraft at the
moment.

Hopefully the bug will be ironed out, like I say, on Debian 11 everything
worked fine.

**Comment by SatoriHoshiAiko** [comment]
Sorry just going from my Debian system. It looks like the default is

CREATE TABLE discordsrv_accounts (a int);
CREATE TABLE discordsrv_codes (a int);

When using the prefix discordsrv_ in the config.yml (that’s what I did for
ease of use)

I am not good with MySQL but I used (a int) in order to generate a first
column and create the tables required. But creating the tables manually is
kind of complicated for a very modest use of MySQL.

Honestly, I think it would be making these tables by default. On Debian 11
I think all I did was create a database. The create tables part I never
manually entered in _accounts _codes. I can’t remember but I believe all I
did was create a database minecraft; and that was that.

If I was having a connection problem it would make sense that it didn’t go
and make the tables on its own. But honestly using Kali (and I can’t change
distribution because I use this system for a lot of uses, otherwise I
wouldn’t also already have a Debian system) most likely causes concerns.
The versioning of MySQL on its own is probably creating difficulties.
Actually with Kali I have to install mysql-community-server as a Debian 11
version. So it is already incompatible from the point of installation where
there are external concerns with the system.

Anyway, would be nice to actually test with a working Minecraft account
again is all. For now will have to come back to it.
