### ISSUE TITLE
DiscordSRV no longer translating certain emojis

### ISSUE THREAD

**Issue by ubdeadhaha** [DiscordSRV/DiscordSRV#1626]
### Expected behavior

The plugin should turn emoji codes into their proper emoji

### Actual behavior

Something is causing certain emojis to not translate. I believe it may be the underscores.
![Screenshot (660)](https://github.com/DiscordSRV/DiscordSRV/assets/125194180/6428781c-7f3f-4f8b-b7b8-f3a3a1277d68)

### Steps to reproduce

This may be due to the underscore, I am not too sure.

### Server software and version

Paper-309 MC 1.20.2

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by J-295** [comment]
I was able to reproduce this issue in the latest snapshot by enabling `Experiment_WebhookChatMessageDelivery`.
Default emojis worked but not custom emojis, including ones that contained only a-z characters.
Sending an emoji mention worked (`<:NAME:ID>`).

**Comment by Cronosus** [comment]
have same problem. some smiles were fixed by setting  
DiscordChatChannelEmojiBehavior and DiscordChatChannelEmoteBehavior to show
but cuso ones dont work, and some users still see some emojis as white square

**Comment by ubdeadhaha** [comment]
This is fixed by updating your plugin, LoneDev no longer supports these versions so you should update your server along with the plugin.

**Comment by J-295** [comment]
@Cronosus That is for emojis being sent in the opposite direction. Create a support ticket on our Discord server to discuss this: https://discordsrv.com/discord.

@0x484 The latest release doesn't have a fix for this, hence the issue still being open. Stay subscribed to this issue if you'd like updates on it.

@ubdeadhaha I'm unsure how "LoneDev" is related to this issue, perhaps you sent this comment to the wrong location?

**Comment by ubdeadhaha** [comment]
> @Cronosus That is for emojis being sent in the opposite direction. Create a support ticket on our Discord server to discuss this: https://discordsrv.com/discord.
> 
> @0x484 The latest release doesn't have a fix for this, hence the issue still being open. Stay subscribed to this issue if you'd like updates on it.
> 
> @ubdeadhaha I'm unsure how "LoneDev" is related to this issue, perhaps you sent this comment to the wrong location?

Ah wrong post, thought this was my post on ItemsAdder which had an issue with emojis!

**Comment by Sewdohe** [comment]
My issue is no matter how I send the emoji, it shows the entire emoji ID:
![image](https://github.com/user-attachments/assets/ef89d7ad-45c9-4c1f-9e3b-f2465bd62492)

**Comment by granny** [comment]
Fixed on the latest snapshot: https://snapshot.discordsrv.com/
